version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - zip -r build.zip src
      - echo Zipped
  post_build:
    commands:
      - ls
artifacts:
  files:
    - build.zip
